name: Docker Image CI

on:
  push:
    branches: [ "prod" ]
  pull_request:
    branches: [ "prod" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        USER: ${{secrets.DOCKER_USER}}
        PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $USER -p $PASSWORD
    - name: Build the Docker image and push
      env:
        USER: ${{secrets.DOCKER_USER}}
      run: docker build . -t ${USER}/cyberbyson-bot:$(grep "tag:" cyberbyson-bot/values.yaml | awk '{print $2}' | tr -d '"') -t ${USER}/cyberbyson-bot:latest && docker push ${USER}/cyberbyson-bot --all-tags